# Default values for stateful-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default

stateful:
  image: k8s.gcr.io/nginx-slim:0.8
  port: 8080
  replicas: 1
  accessMode: ReadWriteMany
  storage: 1Gi

service:
  port: 8080
  targetPort: 8080
  protocol: TCP
  type: NodePort