apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: nginx # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "nginx"
  replicas: {{ .Values.stateful.replicas }}
  template:
    metadata:
      labels:
        app: nginx # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: {{ .Values.stateful.image }}
        ports:
        - containerPort: {{ .Values.stateful.port }}
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ {{ .Values.stateful.accessMode }} ]
      resources:
        requests:
          storage: {{ .Values.stateful.storage }}